server {
  listen 5555;
  listen [::]:5555;

  server_name _;

  location / {
    root /opt/aria2-webui/; 
    try_files $uri $uri/ /index.html;
  }
  location /data {
    alias /opt/data;
    autoindex on;
  }
  location /jsonrpc {
    proxy_pass http://localhost:6800/jsonrpc;
  }
}
