map $http_upgrade $connection_upgrade {
     default upgrade;
     '' close;
}

server {
  listen 5555;
  listen [::]:5555;

  server_name _;

  location / {
    root /opt/aria2-webui/; 
    try_files $uri $uri/ /index.html;
  }
  location /data {
    alias /opt/data;
    autoindex on;
  }
  location /jsonrpc {
    proxy_pass http://localhost:6800/jsonrpc;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_read_timeout 86400;
  }
}
